name: "TestProject job runner"
description: "GitHub Action for running TestProject job"
author: "Ryan Howard"
inputs:
  ProjectId:
    description: "The Id of the TestProject Project you wish to use"
    required: true
  JobId:
    description: "The Id of the TestProject Job you wish to run"
    required: true
  AuthorisationsToken:
    description: "The TestProject API Auth token"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
