name: "TestProject job runner"
description: "GitHub Action for running TestProject job"
author: "Ryan Howard"
inputs:
  project_id:
    description: "The Id of the TestProject Project you wish to use"
    required: true
  job_id:
    description: "The Id of the TestProject Job you wish to run"
    required: true
  authorisation_token:
    description: "The TestProject API Auth token"
    required: true
  interval_time:
    description: "The interval in seconds in which the status of a job will be checked"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
